// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Reflection.PortableExecutable;


namespace System.Reflection.Metadata.ReadyToRun
{
    /// <summary>
    /// Structural projection of the DelayLoadMethodCallThunks section (section 106).
    /// Exposes the opaque executable byte range containing architecture-specific delay-load thunks.
    /// </summary>
    /// <remarks>
    /// The thunks are compact, architecture-dependent stubs generated by the compiler.
    /// Individual thunk boundaries are NOT encoded in the section; the section is an
    /// opaque blob. The architecture can be determined from <see cref="Architecture"/>.
    /// </remarks>
    public sealed class DelayLoadMethodCallThunksSection
    {
        /// <summary>The raw file offset of the thunk blob.</summary>
        public int FileOffset { get; }

        /// <summary>The byte length of the thunk blob.</summary>
        public int Length { get; }

        /// <summary>Target machine architecture of the thunks.</summary>
        public Machine Architecture { get; }

        internal DelayLoadMethodCallThunksSection(int fileOffset, int length, Machine architecture)
        {
            FileOffset = fileOffset;
            Length = length;
            Architecture = architecture;
        }
    }

    public partial class ReadyToRunReader
    {
        /// <summary>
        /// Returns a structural descriptor of the DelayLoadMethodCallThunks section.
        /// The section is an opaque byte range; no individual thunk boundaries are encoded.
        /// </summary>
        public DelayLoadMethodCallThunksSection GetDelayLoadMethodCallThunksSection(ReadyToRunSection section)
        {
            // When Size == 0 the section is empty; there is no content to map, so skip the RVA lookup.
            int fileOffset = section.Size > 0 ? GetOffsetForRVA(section.RelativeVirtualAddress) : 0;
            return new DelayLoadMethodCallThunksSection(fileOffset, section.Size, Machine);
        }
    }
}
