// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Reflection.Metadata.ReadyToRun
{
    /// <summary>
    /// Structural projection of the DelayLoadMethodCallThunks section (section 106).
    /// Exposes the opaque executable byte range containing architecture-specific delay-load thunks.
    /// </summary>
    /// <remarks>
    /// The thunks are compact, architecture-dependent stubs generated by the compiler.
    /// Individual thunk boundaries are NOT encoded in the section; the section is an
    /// opaque blob. The target architecture remains available from
    /// <see cref="ReadyToRunReader.Machine"/>.
    /// </remarks>
    public sealed class DelayLoadMethodCallThunksSection
    {
        /// <summary>The section RVA encoded in the ReadyToRun section directory.</summary>
        public ImageRVA SectionRva { get; }

        /// <summary>The byte length of the thunk blob.</summary>
        public int Length { get; }

        internal DelayLoadMethodCallThunksSection(ImageRVA sectionRva, int length)
        {
            SectionRva = sectionRva;
            Length = length;
        }
    }

    public partial class ReadyToRunReader
    {
        /// <summary>
        /// Returns a structural descriptor of the DelayLoadMethodCallThunks section.
        /// The section is an opaque byte range; no individual thunk boundaries are encoded.
        /// </summary>
        public DelayLoadMethodCallThunksSection GetDelayLoadMethodCallThunksSection(ReadyToRunSection section)
        {
            ValidateAndGetSectionOffset(
                section,
                Internal.Runtime.ReadyToRunSectionType.DelayLoadMethodCallThunks,
                nameof(GetDelayLoadMethodCallThunksSection));
            return new DelayLoadMethodCallThunksSection(section.RelativeVirtualAddress, section.Size);
        }
    }
}
